apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    server: app
  template:
    metadata:
      labels:
        env: test
        server: app
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 8080