apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    server: web
  template:
    metadata:
      labels:
        env: test
        server: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
